### YamlMime:ManagedReference
items:
- uid: ASEProjectTest.GlobalConfigTest
  commentId: T:ASEProjectTest.GlobalConfigTest
  id: GlobalConfigTest
  parent: ASEProjectTest
  children:
  - ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled
  - ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX
  - ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY
  - ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize
  langs:
  - csharp
  - vb
  name: GlobalConfigTest
  nameWithType: GlobalConfigTest
  fullName: ASEProjectTest.GlobalConfigTest
  type: Class
  source:
    remote:
      path: ASEProjectTest/GloabalCofigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Ayush2487342.git
    id: GlobalConfigTest
    path: ASEProjectTest/GloabalCofigTest.cs
    startLine: 12
  assemblies:
  - ASEProjectTest
  namespace: ASEProjectTest
  summary: Tests to ensure that the GlobalConfig static properties behave as expected.
  example: []
  syntax:
    content: >-
      [TestClass]

      public class GlobalConfigTest
    content.vb: >-
      <TestClass>

      Public Class GlobalConfigTest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute.#ctor
    arguments: []
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX
  commentId: M:ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX
  id: TestSetAndGetMaxX
  parent: ASEProjectTest.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxX()
  nameWithType: GlobalConfigTest.TestSetAndGetMaxX()
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX()
  type: Method
  source:
    remote:
      path: ASEProjectTest/GloabalCofigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Ayush2487342.git
    id: TestSetAndGetMaxX
    path: ASEProjectTest/GloabalCofigTest.cs
    startLine: 18
  assemblies:
  - ASEProjectTest
  namespace: ASEProjectTest
  summary: Tests that the MaxX property can be set and retrieved correctly.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxX()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxX()
  overload: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY
  commentId: M:ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY
  id: TestSetAndGetMaxY
  parent: ASEProjectTest.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetMaxY()
  nameWithType: GlobalConfigTest.TestSetAndGetMaxY()
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY()
  type: Method
  source:
    remote:
      path: ASEProjectTest/GloabalCofigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Ayush2487342.git
    id: TestSetAndGetMaxY
    path: ASEProjectTest/GloabalCofigTest.cs
    startLine: 34
  assemblies:
  - ASEProjectTest
  namespace: ASEProjectTest
  summary: Tests that the MaxY property can be set and retrieved correctly.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetMaxY()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetMaxY()
  overload: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled
  commentId: M:ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled
  id: TestSetAndGetIsFillEnabled
  parent: ASEProjectTest.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetIsFillEnabled()
  nameWithType: GlobalConfigTest.TestSetAndGetIsFillEnabled()
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled()
  type: Method
  source:
    remote:
      path: ASEProjectTest/GloabalCofigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Ayush2487342.git
    id: TestSetAndGetIsFillEnabled
    path: ASEProjectTest/GloabalCofigTest.cs
    startLine: 50
  assemblies:
  - ASEProjectTest
  namespace: ASEProjectTest
  summary: Tests that the IsFillEnabled property can be set and retrieved correctly.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetIsFillEnabled()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetIsFillEnabled()
  overload: ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize
  commentId: M:ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize
  id: TestSetAndGetPenSize
  parent: ASEProjectTest.GlobalConfigTest
  langs:
  - csharp
  - vb
  name: TestSetAndGetPenSize()
  nameWithType: GlobalConfigTest.TestSetAndGetPenSize()
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize()
  type: Method
  source:
    remote:
      path: ASEProjectTest/GloabalCofigTest.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-Ayush2487342.git
    id: TestSetAndGetPenSize
    path: ASEProjectTest/GloabalCofigTest.cs
    startLine: 66
  assemblies:
  - ASEProjectTest
  namespace: ASEProjectTest
  summary: Tests that the PenSize property can be set and retrieved correctly.
  example: []
  syntax:
    content: >-
      [TestMethod]

      public void TestSetAndGetPenSize()
    content.vb: >-
      <TestMethod>

      Public Sub TestSetAndGetPenSize()
  overload: ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize*
  attributes:
  - type: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
    ctor: Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.#ctor
    arguments: []
references:
- uid: ASEProjectTest
  commentId: N:ASEProjectTest
  href: ASEProjectTest.html
  name: ASEProjectTest
  nameWithType: ASEProjectTest
  fullName: ASEProjectTest
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX*
  commentId: Overload:ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX
  href: ASEProjectTest.GlobalConfigTest.html#ASEProjectTest_GlobalConfigTest_TestSetAndGetMaxX
  name: TestSetAndGetMaxX
  nameWithType: GlobalConfigTest.TestSetAndGetMaxX
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxX
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY*
  commentId: Overload:ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY
  href: ASEProjectTest.GlobalConfigTest.html#ASEProjectTest_GlobalConfigTest_TestSetAndGetMaxY
  name: TestSetAndGetMaxY
  nameWithType: GlobalConfigTest.TestSetAndGetMaxY
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetMaxY
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled*
  commentId: Overload:ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled
  href: ASEProjectTest.GlobalConfigTest.html#ASEProjectTest_GlobalConfigTest_TestSetAndGetIsFillEnabled
  name: TestSetAndGetIsFillEnabled
  nameWithType: GlobalConfigTest.TestSetAndGetIsFillEnabled
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetIsFillEnabled
- uid: ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize*
  commentId: Overload:ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize
  href: ASEProjectTest.GlobalConfigTest.html#ASEProjectTest_GlobalConfigTest_TestSetAndGetPenSize
  name: TestSetAndGetPenSize
  nameWithType: GlobalConfigTest.TestSetAndGetPenSize
  fullName: ASEProjectTest.GlobalConfigTest.TestSetAndGetPenSize
